### ISSUE TITLE
BHL stats are wrong

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/dashboard#64]
> Dear ALA team,
I’m just looking at the Dashboard page on the ALA and notice that it’s way out of date for the Biodiversity Heritage Library. I don’t know how you’re getting data from BHL but it needs refreshing as it’s about 10 million pages short!
 
> Also, it would be great if the dashboard tile title of Biodiversity heritage library could be turned into a link. The correct one is http://biodiversitylibrary.org
 
> Thanks, Ely

**Comment by javier-molina** [comment]
Hi @nickdos 

These are the current values for BHL panel in ala-install:

"bhlCounts": {
	"pages": 39184197,
	"titles": 56175,
	"volumes": 106715,
	"publishers": 1695
	},


Do you have the new values or have a pointer where I can source them?

Btw publishers is not shown at the moment, if there is no objection I will add that to the panel.

Thanks
Javier

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/dashboard/review/DASHBOARD-CR-1

**Comment by nickdos** [comment]
Those stats are probably being updated via a REST call to a BHL server... is probably a Grails service(?).

**Comment by nickdos** [comment]
Only stats I could find are on the BHL home page near the bottom-right. http://biodiversitylibrary.org/

![image](https://cloud.githubusercontent.com/assets/532845/14946159/5ac67998-1061-11e6-95a2-53b0bd45f86e.png)

Although there are web services - I couldn't find an "operation" to get the stats...

http://www.biodiversitylibrary.org/api2/docs/docs.html

So I'm thinking we'll need to scrape the values from the homepage for now. I'd suggest using [jsoup](https://jsoup.org/) for this.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/dashboard/review/DASHBOARD-CR-1

**Comment by sat01a** [comment]
Looks like this ticket is reviewed by Nick. Closing the issue.
